### PR TITLE
Add support for high DPI and responsive signatures

### PR DESCRIPTION
**Pull request by Teemu**
Our goal is to create responsive signature. This turns out to be a bit problematic since the underlying library is very much bitmap based. This approach uses predefined size and allows to resize canvas with CSS.

This also fixes problems with high DPI screens and resizing browser window (such as #16 or #11).

See [our responsive demo](https://rawgit.com/fastmonkeys/angular-signature/fix-high-dpi/responsive_demo.html).

### CODE REVIEW

**Comment by Sarfaraaz** [comment]
Hi,

Thanks for your contribution. I've taken a look at your demo, but there's a rather big issue with the changes you've made (or at least judging from the demo).  You've given the canvas a specific size and added full-width styling to it which will have the canvas render the strokes in a much lower quality. Additionally clearing the canvas will only clear the size you've defined in the canvas element.

If you could take care of these issues I'll merge this.

**Comment by Teemu** [comment]
> You've given the canvas a specific size and added full-width styling to it which will have the canvas render the strokes in a much lower quality.

That's correct. The demo is just showcasing how the displayed resolution and the bitmap resolution can now be different. I recommend setting `max-width: 1000px` (as the canvas width is 1000px) if you want to make sure the strokes don't look bad.

The normal, fixed width way is going to continue to work regardless (as seen in `demo.html`).

> Additionally clearing the canvas will only clear the size you've defined in the canvas element.

I fixed this. Nice catch.

**Comment by Teemu** [comment]
I noticed that there is [a PR for underlying library](https://github.com/szimek/signature_pad/pull/100) that would solve the css scaling issue there. What a mess 😱 .

**Comment by jasny** [comment]
Skipping this PR as it should be solved in szimek/signature_pad#100.

**Pull request closed without merging**
